### ISSUE TITLE
Should show feedback when no flights found.

### ISSUE THREAD

**Issue by dwlf** [ToddGreenstein/try-cb-nodejs#11]
Should show feedback when no flights found. eg. OAK <-> SFO

ENV

```
$ git describe --long --dirty --abbrev=10 --tags --always
8d06139abd-dirty
* added git to dockerfile
```

**Comment by dwlf** [comment]
This can only lead to an app crash. After a crash and restart let Firefox automatically create account and login.
1. Enter OAK and SFO
   -> no results
2. Click "User Profile" icon.

```
QUERY: SELECT airportname FROM `travel-sample` WHERE faa ='OAK'
QUERY: SELECT airportname FROM `travel-sample` WHERE faa ='SFO'
QUERY: SELECT faa as fromAirport,geo FROM `travel-sample` WHERE airportname = 'Metropolitan Oakland Intl' UNION SELECT faa as toAirport,geo FROM `travel-sample` WHERE airportname = 'San Francisco Intl'
QUERY: SELECT faa as fromAirport,geo FROM `travel-sample` WHERE airportname = 'San Francisco Intl' UNION SELECT faa as toAirport,geo FROM `travel-sample` WHERE airportname = 'Metropolitan Oakland Intl'
QUERY: SELECT r.id, a.name, s.flight, s.utc, r.sourceairport, r.destinationairport, r.equipment FROM `travel-sample` r UNNEST r.schedule s JOIN `travel-sample` a ON KEYS r.airlineid WHERE r.sourceairport='OAK' AND r.destinationairport='SFO' AND s.day=3 ORDER BY a.name
QUERY: SELECT r.id, a.name, s.flight, s.utc, r.sourceairport, r.destinationairport, r.equipment FROM `travel-sample` r UNNEST r.schedule s JOIN `travel-sample` a ON KEYS r.airlineid WHERE r.sourceairport='SFO' AND r.destinationairport='OAK' AND s.day=4 ORDER BY a.name
/usr/src/app/model/auth.js:111
            done(null,found[0].flights);
                              ^
TypeError: Cannot read property 'flights' of undefined
    at /usr/src/app/model/auth.js:111:31
    at /usr/src/app/node_modules/ottoman/lib/ottoman.js:291:9
    at /usr/src/app/node_modules/ottoman/lib/storeadapter.js:29:7
```
