### ISSUE TITLE
Cannot build.  Gettting an error with npm install couchbase@2.3.7

### ISSUE THREAD

**Issue by djangofan** [ToddGreenstein/try-cb-nodejs#19]
Looks to be a problem with `npm install couchbase@2.3.7`  during build.     NOTE:  I ran `npm install couchbase`  on my machine and that worked ok.

```
../src/couchbase_impl.cc:454:46: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
            Local<Object> metaObj = dataRes->ToObject();
                                             ^
/Users/x/.node-gyp/10.13.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/x/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
11 warnings and 1 error generated.
make: *** [Release/obj.target/couchbase_impl/src/couchbase_impl.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/x/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/x/.nvm/versions/node/v10.13.0/bin/node" "/Users/x/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/x/Documents/GitHub/try-cb-nodejs-5.0/node_modules/couchbase
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! couchbase@2.3.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the couchbase@2.3.7 install script.
```

> 12:19 $ ignite doctor
> System
>   platform           darwin                                                                                                    
>   arch               x64                                                                                                       
>   cpu                8 cores                                              Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz  
>   directory          /Users/x/workspace/FAL/falcon-app-automation                                                        
> 
> JavaScript
>   node               10.13.0      /Users/x/.nvm/versions/node/v10.13.0/bin/node  
>   npm                6.9.0        /Users/x/.nvm/versions/node/v10.13.0/bin/npm   
>   yarn               1.12.3       /usr/local/bin/yarn                                  
> 
> React Native
>   react-native-cli   2.0.1       
> 
> Ignite
>   ignite             2.2.3        /usr/local/bin/ignite  
> 
> Android
>   java               1.8.0_101    /Users/x/.asdf/shims/java     
>   android home       -            /Users/x/Library/Android/sdk  
> 
> iOS
>   xcode              10.0

**Comment by djangofan** [comment]
Sorry, this bug was found in a fork of your project:  https://github.com/couchbaselabs/try-cb-nodejs

Fixed it by changing couchbase version to 2.6.3 in the package.json
