### ISSUE TITLE
OAK <-> SFO crashes app

### ISSUE THREAD

**Issue by dwlf** [ToddGreenstein/try-cb-nodejs#9]
OAK <-> SFO crashes app.

Search for flights from SFO to/from SFO and the app crashes.

```
QUERY: SELECT faa as fromAirport,geo FROM `travel-sample` WHERE airportname = 'Metropolitan Oakland Intl' UNION SELECT faa as toAirport,geo FROM `travel-sample` WHERE airportname = 'sfo'
/usr/src/app/node_modules/haversine/haversine.js:21
    var dLat = toRad(end.latitude - start.latitude)
                                         ^
TypeError: Cannot read property 'latitude' of undefined
    at haversine (/usr/src/app/node_modules/haversine/haversine.js:21:42)
    at /usr/src/app/model/flightPath.js:45:24
    at /usr/src/app/model/db.js:209:9
    at N1qlQueryResponse.<anonymous> (/usr/src/app/node_modules/couchbase/lib/bucket.js:694:7)
    at N1qlQueryResponse.emit (events.js:110:17)
    at /usr/src/app/node_modules/couchbase/lib/bucket.js:641:15
```

ENV

```
$ git describe --long --dirty --abbrev=10 --tags --always
8d06139abd-dirty
* added git to dockerfile
```

**Comment by dwlf** [comment]
Oh, actually the symptom seems to be caused when an airport is left as the airport 3 letter code.

**Comment by dwlf** [comment]
"Find Flights" button should only be enabled once the airports have been validated.
